apiVersion: apps/v1
kind: Deployment
metadata:
  name: vnc-browser-user1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vnc-browser-user1
  template:
    metadata:
      labels:
        app: vnc-browser-user1
    spec:
      containers:
      - name: chrome-vnc
        image: pardeepkaur/chrome-vnc:latest  # Full image name
        ports:
        - containerPort: 5900
        volumeMounts:
        - mountPath: "/tmp/chrome-data"
          name: user1-storage
      volumes:
      - name: user1-storage
        persistentVolumeClaim:
          claimName: user1-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vnc-browser-user2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vnc-browser-user2
  template:
    metadata:
      labels:
        app: vnc-browser-user2
    spec:
      containers:
      - name: chrome-vnc
        image: pardeepkaur/chrome-vnc:latest  # Full image name
        ports:
        - containerPort: 5900
        volumeMounts:
        - mountPath: "/tmp/chrome-data"
          name: user2-storage
      volumes:
      - name: user2-storage
        persistentVolumeClaim:
          claimName: user2-pvc
