apiVersion: apps/v1
kind: Deployment
metadata:
  name: user1-deployment
  labels:
    app: vnc-browser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vnc-browser
  template:
    metadata:
      labels:
        app: vnc-browser
    spec:
      containers:
      - name: vnc-browser
        image: amd64/ubuntu:vnc-browser
        ports:
        - containerPort: 5900
        volumeMounts:
        - name: chrome-data
          mountPath: /home/ubuntu/cloud-browser/vol/user1-data
      volumes:
      - name: chrome-data
        persistentVolumeClaim:
          claimName: user1-pvc
