apiVersion: v1
kind: PersistentVolume
metadata:
  name: user1-pv  # Unique name for each user's PV
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/home/ubuntu/cloud-browser/vol/user1-data"  # Path for user1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user1-pvc  # Unique name for each user's PVC
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
