apiVersion: v1
kind: PersistentVolume
metadata:
  name: user1-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/ubuntu/cloud-browser/vol/user1-data
