apiVersion: v1
kind: Service
metadata:
  name: vnc-browser-service
  labels:
    app: vnc-browser
spec:
  selector:
    app: vnc-browser
  ports:
  - protocol: TCP
    port: 5900
    targetPort: 5900
  type: NodePort
