apiVersion: v1
kind: Service
metadata:
  name: vnc-browser-user1-service
spec:
  selector:
    app: vnc-browser-user1
  ports:
    - protocol: TCP
      port: 5900
      targetPort: 5900
      nodePort: 30001  # Expose on a specific port if using NodePort
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: vnc-browser-user2-service
spec:
  selector:
    app: vnc-browser-user2
  ports:
    - protocol: TCP
      port: 5900
      targetPort: 5900
      nodePort: 30002  # Expose on a specific port if using NodePort
  type: NodePort

