apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vnc-browser.fullname" . }}-{{ .Values.employee.id }}
  labels:
    {{- include "vnc-browser.labels" . | nindent 4 }}
    employee-id: "{{ .Values.employee.id }}"
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "vnc-browser.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "vnc-browser.labels" . | nindent 8 }}
        employee-id: "{{ .Values.employee.id }}"
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "vnc-browser.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: EMPLOYEE_ID
              value: "{{ .Values.employee.id }}"
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: employee-data
              mountPath: /data  # Adjust path as necessary
      volumes:
        - name: employee-data
          persistentVolumeClaim:
            claimName: pvc-{{ .Values.employee.id }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

# Persistent Volume Definition
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-{{ .Values.employee.id }}
  labels:
    app: vnc-browser
    employee-id: "{{ .Values.employee.id }}"
spec:
  capacity:
    storage: {{ .Values.storage.size | default "1Gi" }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/ubuntu/cloud-browser/vol/employee-{{ .Values.employee.id }}  # Update path for each employee

# Persistent Volume Claim Definition
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-{{ .Values.employee.id }}
  labels:
    app: vnc-browser
    employee-id: "{{ .Values.employee.id }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size | default "1Gi" }}

# Autoscaling configuration (when enabled)
{{- if .Values.autoscaling.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "vnc-browser.fullname" . }}-hpa
  labels:
    {{- include "vnc-browser.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "vnc-browser.fullname" . }}-{{ .Values.employee.id }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
  {{- if .Values.autoscaling.targetMemoryUtilizationPercentage }}
  targetMemoryUtilizationPercentage: {{ .Values.autoscaling.targetMemoryUtilizationPercentage }}
  {{- end }}
{{- end }}

