apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vnc-browser-pvc-{{ .Values.employee.id }}
  labels:
    employee-id: "{{ .Values.employee.id }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}  # The storage size comes from the values file
  volumeName: vnc-browser-{{ .Values.employee.id }}-pv  # Dynamically reference the PV using employee ID
